### ISSUE TITLE
qwik script no longer works with qwik-nx

### ISSUE THREAD

**Issue by st-clair-clarke** [qwikifiers/qwik-nx#134]
### Current Behavior

pnpm run qwik no longer executes in qwik-nx

### Expected Behavior

qwik script to execute and allow the integrations of specific third party packages

### Steps to Reproduce

1. Install qwik with qwik-nx
2. Go to the root of the installation folder and run pnpm | npm qwik - script not found

### Nx Report

```shell
Cannot find qwik script
```

**Comment by dmitry-stepanenko** [comment]
Qwik cli will not work in the nx workspace due to the differences in project layout. We're working on adding integrations to have the feature parity with the qwik cli using nx generators. 

If you need any specific integration, please consider opening an issue with a feature request for it. This will help us to prioritize what we should deliver first
