### ISSUE TITLE
Add E2E tests for this repo

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-nx#65]
we need E2E tests to verify that our plugins work in integration

Test cases that should be present.

Library:
- [ ] buildable library can be built
- [ ] tests pass (right now it actually fails because of a bug on a qwik side)
- [ ] lint passes

Application:
- [ ] tests pass
- [ ] playwright/cypress e2e tests pass. We should generate an e2e project and put real e2e tests in it. Those tests should go through the app and check interactions (do some stuff on "flower" page, add todos on "todo" page)
- [ ] lint

Preset:
- [ ] attempt to use a preset generator with current version of Nx in a tmp dir, that is outside of the project repo. This is important to make sure repo's dependencies are not pulled to a newly generated project. We should either publish the package to a local registry and run `npx create-nx-workspace` or use `npm pack` and then create an empty workspace and install qwik-nx by a full path (`"qwik-nx": "/Users/..../qwik-nx-0.12.1.tgz"`

Cloudflare integration:
- [ ] application can be built with cloudflare configuration (newly generated separate target)
- [ ] application can be served with wrangler

qwikNxVite
- [ ] verify it is able to build apps with components imported from libs
- [ ] add `debug: true` to the plugin's params and verify it correctly resolves app's dependent libraries based on project graph (just check that it prints the expected list)

Other (by generating a qwik app):
- [ ] can use route generator and it opens correctly (e.g. check response html using `fetch`)
- [ ] can use component generator
- [ ] can use tailwind

**Comment by gioragutt** [comment]
I’ll take this one 👍🏻

**Comment by shairez** [comment]
thanks brother!

**Comment by dmitry-stepanenko** [comment]
Thanks @gioragutt!

**Comment by dmitry-stepanenko** [comment]
Leaving here test cases that I think should be present.

Library:
- buildable library can be built
- tests pass (right now it actually fails because of a bug on a qwik side)
- lint passes

Application:
- tests pass
- playwright/cypress e2e tests pass. We should generate an e2e project and put real e2e tests in it. Those tests should go through the app and check interactions (do some stuff on "flower" page, add todos on "todo" page)
- lint

Preset:
- attempt to use a preset generator with current version of Nx in a tmp dir, that is outside of the project repo. This is important to make sure repo's dependencies are not pulled to a newly generated project. We should either publish the package to a local registry and run `npx create-nx-workspace` or use `npm pack` and then create an empty workspace and install qwik-nx by a full path (`"qwik-nx": "/Users/..../qwik-nx-0.12.1.tgz"`

Cloudflare integration:
- application can be built with tailwind configuration (newly generated separate target)
- application can be served with wrangler

Other (by generating a qwik app):
- can use route generator and it opens correctly (e.g. check response html using `fetch`)
- can use component generator
- can use tailwind
